### ISSUE TITLE
Bad AVX support detection in VM environments

### ISSUE THREAD

**Issue by haxelion** [quarkslab/QBDI#19]
AVX support is dynamically detected using CPUID to determine wether the kernel enabled AVX registers save/restore during context switches. This works on regular machines however VM software are quite bad at faking CPUID and tend to provide results for the host rather than the guest.

The consequence is that, a VM not supporting AVX but running on a host supporting it will be detected as supporting AVX. This results in a SIGILL on the first context switch made by QBDI.

While we offer a FORCE_DISABLE_AVX flag at compilation, our pre-build packages are still broken in VM environment. We thus need a better fix.

**Comment by nezetic** [comment]
Thanks to a beta tester feedback on our IRC channel, we have found the real issue. We simplify mismatched AXV VEXTRACTF128 and AVX2 VEXTRACTI128 instructions...

This commit 141d9006083470f77d29572b6e1dd5c8f86c79ba is proposing a fix by switching to the AVX instruction. Performances impact study is still to be conducted.

**Comment by nezetic** [comment]
Our studies let us think that this patch doesn’t have any real impact and indeed fix AVX support on non AVX 2 CPU.
Performance tests conducted on Core i5 and i7 CPUs does not reveal any significant overhead.
I've merged the patch.
