### ISSUE TITLE
Comparison issue

### ISSUE THREAD

**Issue by Carmot** [quarkslab/QBDI#24]
https://github.com/quarkslab/QBDI/blob/aca7930f6516660545704ab3171cc0c1a32e155a/src/Patch/X86_64/PatchGenerator_X86_64.h#L329

https://github.com/quarkslab/QBDI/blob/aca7930f6516660545704ab3171cc0c1a32e155a/src/Patch/X86_64/PatchGenerator_X86_64.h#L425

Should it be compared against '1' instead of '2'? It is the same comparison twice.

**Comment by haxelion** [comment]
Yes it should! Nice catch!
The funny thing is this code path can never be triggered because there exist no 1 byte read instructions marked as a stack read :-)

**Comment by nezetic** [comment]
Thanks for reporting this. I've merged the fix in the dev branch.
