### ISSUE TITLE
Host making use of Dynamic Memory

### ISSUE THREAD

**Issue by johnfxgalea** [quarkslab/QBDI#27]
Does the C API allow the host (say in the main function) to use dynamic memory, making use of malloc/free? From all the examples I have seen in the docs, counters which are passed to callback functions are never stored on the heap.

I am more concerned whether the use of the heap allocator by the host will break its transparency for the guest. Is this the case please?

**Comment by johnfxgalea** [comment]
Having looked at the docs, I believe I am required to use qbdi_alignedAlloc(). Is this correct?

**Comment by haxelion** [comment]
Yes you can use dynamic memory allocation inside your tool. 

However the situation is a bit complex: we use the same libc for the host and the guest which means that, to avoid deadlocks, we blacklist `libc.so` (and  `libd.so`) from our instrumentation. An exemple of such blacklisting is done [here](https://github.com/quarkslab/QBDI/blob/master/tools/QBDIPreload/src/linux_preload.c#L180).

**Comment by johnfxgalea** [comment]
I see, thanks for your reply! So library transparency is not attained at all; meaning that, for instance, the heap data layout using a deterministic allocator will be different when using QBDI in comparison to running the original program natively.

**Comment by haxelion** [comment]
Yes indeed we don’t have library transparency at this point and the heap is heavely tainted by QBDI.

If someone managed to hack a LLVM build using a cutom `libc` and C++ STL we could work that out. But so far we have not investigated the idea.
