### ISSUE TITLE
qbdi_getInstAnalysis does not work properly in VMEvent callbacks

### ISSUE THREAD

**Issue by Axi0m-S** [quarkslab/QBDI#28]
1. Description :
 When using **qbdi_getInstAnalysis** in some VMEvent callbacks (eg : **QBDI_BASIC_BLOCK_ENTRY**), it does not yield the expected result.

2. Steps to reproduce :
* Instrument any function with basicBlocks
* define a callback printing **vmState->basicBlockStart** and **instAnalysis->address** (retrieved with **qbdi_getInstAnalysis**)
* Run the instrumentation

3. Expected result :
**vmState->basicBlockStart** and **instAnalysis->address** should be the same

4. Actual result :
**instAnalysis->address**  is one instruction behind. 

Since the instruction modifying the program counter has not been executed yet, instAnalysis has not been updated, giving the last instruction value.

Output from test :
	VMEvent Callback on : QBDI_BASIC_BLOCK_ENTRY
vmState->basicBlockStart = 0x55787a3a0f07	 instAnalysis->address = 0x55787a3a0f0f

**Comment by haxelion** [comment]
@Axi0m-S: Can you check PR #31 to see if it fixes it?

**Comment by Axi0m-S** [comment]
Looks good to me.

**Comment by nezetic** [comment]
Nice find. Patch looks good. Merged. Closing.
