### ISSUE TITLE
[Question] How do you set RIP in pyQBDI ?

### ISSUE THREAD

**Issue by bruce30262** [quarkslab/QBDI#53]
Let's say I have a program with the following assembly code:  
```
0x10001:  inst1
0x10003:  inst2
0x10006:  inst3
0x10008:  inst4
```

now I add a call back function at address 0x10001 :  

```python
def cb1(vm, gpr, fpr, data):
   # do some stuff.......
    gpr.rip = 0x10008  # I want to jump to 0x10008
    vm.setGPRState(gpr)
    return pyqbdi.CONTINUE

def pyqbdipreload_on_run(vm, start, stop):
    vm.addCodeAddrCB(0x10001, pyqbdi.PREINST, cb1, None)
    vm.run(start, stop)
```
As you can see I want to jump to 0x10008 and skip the instructions from 0x10003 ~ 0x10007  
However the code above won't work  
I've tried add call back function at `pyqbdi.POSTINST` too, still no luck :/  

Is there anyway I can hijack the RIP with pyQBDI ?

**Comment by haxelion** [comment]
Yes it is possible! You simply need to return `pyqbdi.BREAK_TO_VM` instead of `pyqbdi.CONTINUE`
It is not explained in the Python API documentation but it is in the C API documentation: https://qbdi.quarkslab.com/docs/api_c.html#_CPPv28VMAction

**Comment by bruce30262** [comment]
I see. It works as expect now, thx :)
